### ISSUE TITLE
Dependencies issue

### ISSUE THREAD

**Issue by jtsanborn1** [Stable-X/StableNormal#11]
What python did you run on your side? i got a lot of dependencies not found errors. 

env was created based on Python 3.9 and python 3.10

**Comment by aloma85** [comment]
I'm having the same issue. Even in google colab
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cudf-cu12 24.4.1 requires pandas<2.2.2dev0,>=2.0, but you have pandas 2.2.2 which is incompatible.
cudf-cu12 24.4.1 requires pyarrow<15.0.0a0,>=14.0.1, but you have pyarrow 16.0.0 which is incompatible.
dask 2024.8.0 requires click>=8.1, but you have click 8.0.4 which is incompatible.
gcsfs 2024.6.1 requires fsspec==2024.6.1, but you have fsspec 2024.3.1 which is incompatible.
google-colab 1.0.0 requires pandas==2.1.4, but you have pandas 2.2.2 which is incompatible.
google-colab 1.0.0 requires requests==2.32.3, but you have requests 2.31.0 which is incompatible.
jupyter-server 1.24.0 requires anyio<4,>=3.1.0, but you have anyio 4.4.0 which is incompatible.
pytensor 2.25.4 requires filelock>=3.15, but you have filelock 3.14.0 which is incompatible.
torchaudio 2.4.1+cu121 requires torch==2.4.1, but you have torch 2.2.0 which is incompatible.
torchvision 0.19.1+cu121 requires torch==2.4.1, but you have torch 2.2.0 which is incompatible.

```

**Comment by zxbzhineng** [comment]
@hugoycj Hello, will the lack of triton have a negative impact on the inference results?
                    A matching Triton is not available, some optimizations will not be enabled
                    Traceback (most recent call last):
                      File "E:\Anaconda\envs\StableNormal-P\lib\site-packages\xformers\__init__.py", line 55, in _is_triton_available
                        from xformers.triton.softmax import softmax as triton_softmax  # noqa
                      File "E:\Anaconda\envs\StableNormal-P\lib\site-packages\xformers\triton\softmax.py", line 11, in <module>
                        import triton
                    ModuleNotFoundError: No module named 'triton'
